### ISSUE TITLE
Problem with setting mlint dir

### ISSUE THREAD

**Issue by jo-fleck** [ajdm/linter-matlab#10]
Thanks for this package!

I am trying to set the mlint directory (on a mac) in the package settings but I keep getting an error: 

Failed to run MATLAB linter - Directory containing mlint is set to '/Applications/MATLAB_R2016a.app/bin/maci64/mlint'

The directory is correct... any idea what could be the problem? (Would like to avoid adding it to PATH.)

**Comment by jdmanton** [comment]
I believe you need a trailing slash on the path (I am away from my computer at the moment and so can't check). Try setting it to ``/Applications/MATLAB_R2016a.app/bin/maci64/mlint/`` and if that doesn't work let me know.

**Comment by jo-fleck** [comment]
Doesn't work unfortunately. Same error:

Failed to run MATLAB linter - Directory containing mlint is set to '/Applications/MATLAB_R2016a.app/bin/maci64/mlint/'

**Comment by jdmanton** [comment]
I don't have MATLAB 2016a currently (only 2015a), but is ``mlint`` definitely in its own subdirectory in that version? For mine the correct path is ``/Applications/MATLAB_R2015a.app/bin/maci64/``.

**Comment by jo-fleck** [comment]
That's it - thanks a lot!
