### ISSUE TITLE
linter-matlab not compatible with base linter 2.3.0 

### ISSUE THREAD

**Issue by mmikelst** [ajdm/linter-matlab#13]
Base linter 2.3.0 appears to be incompatible with current version of linter-matlab. Updated version on Win10 and Linux Mint 19--in both cases, linter-matlab stopped functioning with no error message. Changelog for base linter mentions removing support for legacy linter APIs.

Confirmed: Rolling back to linter-2.2.0 re-enabled linter-matlab.

**Comment by elpollodiablo84** [comment]
I opened a Pull Request with the updated message needed for the new linter version. It's an easy fix, there are only some different fields names with respect to the old version.

**Comment by smiddy** [comment]
Would be great if this could me merged and published, @ajdm !

**Comment by jdmanton** [comment]
Thanks for the pull request @elpollodiablo84! Sorry for the delay in merging.
