### ISSUE TITLE
Feature request: Temporarily hide the warning list

### ISSUE THREAD

**Issue by abbiekressner** [ajdm/linter-matlab#5]
Thanks for the great plugin! In the future, it would be awesome if you could temporarily hide the warning list. The warning list can sometimes become quite long, and it can be distracting. Anyways, keep up the great work!

**Comment by jdmanton** [comment]
Thanks. The `linter` plugin provides a `toggle` command which you can use to switch off linting and then switch it back on when you're ready. By default there's no keybinding, but you can add one by putting something like the following in your keymap file:

```
'.workspace':
  'ctrl-alt-l': 'linter:toggle'
```

Ideally I'd like to make it possible to hide warnings and only display errors while linting, but I haven't quite worked out how to make that distinction yet (see #2).

**Comment by abbiekressner** [comment]
Awesome! Thanks, @ajdm!
